### ISSUE TITLE
Use a real web server instead of flask debug server

### ISSUE THREAD

**Issue by gracecodes144** [chop-dbhi/data-models-sqlalchemy#18]

**Comment by bruth** [comment]
Are you saying that it should not run in debug mode? Or that it is not performant enough? The `Flask.run` method takes `multithreaded` and/or `processes` to handle more clients, although of course it is not suitable [for the big times](http://stackoverflow.com/a/14823968/407954).

**Comment by gracecodes144** [comment]
Implementing gunicorn was super simple and I've got a local branch with that as the default command when run from the Docker image (which is how the package is deployed to AWS). Just a simple thing to ensure scalability.
