### ISSUE TITLE
Maybe make ER feature optional

### ISSUE THREAD

**Issue by murphyke** [chop-dbhi/data-models-sqlalchemy#20]
It would be nice not to have to install libs for pygraphviz functionality that might not be used.  For Ubuntu, supposedly these libs are graphviz, libgraphviz-dev, and libgraphviz4.  For Debian (official Docker Python, e.g.), the only library required is libgraphviz-dev.

**Comment by gracecodes144** [comment]
I think this is just a documentation problem (and possibly an `import` statement location problem). Installing those libraries is optional and you should only get errors if the `ddl` module is sourced. Also, this is one of the main advantages of having a publicly available Docker image.
