### ISSUE TITLE
Oracle NUMBER(10) incompatible with PostgreSQL SERIAL

### ISSUE THREAD

**Issue by murphyke** [chop-dbhi/data-models-sqlalchemy#40]
This can result in data from an Oracle database failing to load into a PostgreSQL database.

**Comment by gracecodes144** [comment]
Has this happened recently? If not, why not? What's the fix, moving the type to NUMBER(9)?

**Comment by murphyke** [comment]
No, this has not happened in ages and doesn't seem likely to happen again. They were assigning PKs from sequences that they never reset.

NUMBER(9) would fix it, but Oracle's TT_INTEGER type would be a better fit.  TT_INTEGER is a signed 4-byte integer, so it would have the same max value as PostgreSQL's SERIAL type (2147483647).

**Comment by gracecodes144** [comment]
OK, closing.
