### ISSUE TITLE
Automatically pick up the latest data models definitions

### ISSUE THREAD

**Issue by murphyke** [chop-dbhi/data-models-sqlalchemy#51]
@aaron0browne When the data models are updated, it would be good if the DMSA service automatically reflected the changes seen in the data models service. I know the latter gets github webhook notification from chop-dbhi/data-models (as well as checking once per hour).

Some possibilities:

1. DMSA  doesn't cache anything and always hits the DMS (the /models endpoint may be the most expensive, at 1.1MB, but it's still fast enough).
2. DMSA polls http://data-models-service.research.chop.edu/repos to detect when the SHA1 changes.
3. DMSA has a webhook endpoint, triggered by github, and the handler reloads config after a delay.
4. DMSA has a webhook endpoint, triggered by the data models service.

I could do one of these if you want. No. 1 seems the most practical to me.

**Comment by gracecodes144** [comment]
So, to be perfectly honest, I don't really like any of these options because 1 adds extra overhead to every request and 2-4 add extra integrations. What about just rebuilding the cache every hour like the data models service?

**Comment by murphyke** [comment]
Rebuilding the cache every hour is a good option.

**Comment by bruth** [comment]
One concern is that if the DMS updates immediately (when the webhook fires) and the DMSA service doesn't update for at most an hour, this could be confusing to users. (3) should be very easy to implement. There may be a library that already parses and verifies the webhook request from GitHub. If not, the HMAC verification is simple to do.

**Comment by gracecodes144** [comment]
This likes like a pretty easy to use implementation: https://github.com/bloomberg/python-github-webhook

**Comment by bruth** [comment]
Yea that looks straightforward enough.

**Comment by murphyke** [comment]
Re: no. 3, one problem is that the webhook is only going to hit one of the DMSA processes, which can't share data easily. We could add memcached to the mix.

I'm not sure how much you would gain by using memcached versus just viewing the DMS as the cache. I guess there would be some minor performance improvement because the serialized parsed data models would be cached rather than the raw text.

Also, if DMS has some problem starting up, the delay could prevent DMSA from ever updating. To  get around that, we could run a `threading.Timer` function to do updates once per hour. If we wanted to avoid the overhead of N processes all updating once an hour, there could be an `updating` flag and `last_update` timestamp in memcached to coordinate things.

Another way around the complication would be to switch to using greenlet-based concurrency with gunicorn. I don't know anything about that, though. 

Thoughts?

**Comment by bruth** [comment]
> one problem is that the webhook is only going to hit one of the DMSA processes

I am assuming this is referring to Flask running in multi-process mode? Or are there multiple containers running being load balanced?

> I guess there would be some minor performance improvement because the serialized parsed data models would be cached rather than the raw text.

Given how infrequent the data models are updated and requested, I don't think this would ever be an issue.

**Comment by gracecodes144** [comment]
This is a multi-process mode problem, I believe. We are not running multiple containers. So one solution I thought about is just using disk to cache the data models (instead of memcached).

We could also reconsider an update timer approach, but on a tighter schedule than an hour.

**Comment by murphyke** [comment]
> Given how infrequent the data models are updated and requested, I don't think this would ever be an issue.

The "requested" part is why I favored doing no caching at all.

However, file-locking would work. I see that using an `flock`-based solution like [simpleflock](https://github.com/derpston/python-simpleflock) should work on non-NFS filesystems and is immune to the stale lock file problem (i.e. if a process terminates while holding a lock, the OS ensures that the lock is released). It is also good because a timer-based update thread and the Flask webhook handler thread would correctly block each other.
