### ISSUE TITLE
Terraform PR question

### ISSUE THREAD

**Issue by murphyke** [chop-dbhi/data-models-sqlalchemy#55]
@aaron0browne I don't see any terraform-related stuff in master.  2b82df61a0c9a3df31f74fa6623be538b44fbb79 claims to document Terraform deployment and remove deploy configuration, but it removes all the files in `./ci/`.

**Comment by gracecodes144** [comment]
Since the deployment is specific to our instance of the service, I moved the files in to the private github at https://github.research.chop.edu/devops/data-models-sqlalchemy

**Comment by murphyke** [comment]
OK. I can update the README to refer to that repo.

**Comment by murphyke** [comment]
Did that. Closing.
